apiVersion: apps/v1
kind: Deployment
metadata:
  name: wandercult
  namespace: wandercult
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wandercult
  template:
    metadata:
      labels:
        app: wandercult
    spec:
      containers:
        - name: wandercult
          image: noredineba/wandercult:build-26
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: wandercult-config
            - secretRef:
                name: wandercult-secrets
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-pvc