---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: wandercult
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: wandercult
  namespace: wandercult
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  selector:
    app: wandercult
